### ISSUE TITLE
Feature request: create issues on GitLab

### ISSUE THREAD

**Issue by Flink** [nhmood/watson-ruby#114]
I think it would be nice to be able to create issues on GitLab :) (https://github.com/gitlabhq/gitlabhq)

**Comment by pborreli** [comment]
:+1:

**Comment by nhmood** [comment]
This was one of the first additions I was going to take a look at after getting all the preliminary bugs out of the way :)
I can hopefully bust out some support for this in the next couple of days!

**Comment by Flink** [comment]
Nice! :) :+1:

**Comment by sebzur** [comment]
I would vote for that too! :+1:

**Comment by nhmood** [comment]
@Flink @pborreli @sebzur and others, I think I have a working version with GitLab support!

If you guys could test it out and let me know if it is working (or if you have GitLab specific suggestions) that would be great so I can merge it into master.

You can either checkout the [gitlab_support](https://github.com/nhmood/watson-ruby/tree/gitlab_support) branch or you can download the compiled gem [watson-gitlab.gem](http://goosecode.com/watson/watson-gitlab.gem)

**Comment by sebzur** [comment]
Wow! Thanks! 

I'm going to check it this week and for sure I'll let you know how it's working.

Cheers!

**Comment by Flink** [comment]
Seems to work fine! That’s great, thank you! :)
