### ISSUE TITLE
Can 'watson -u' support single file udpate?

### ISSUE THREAD

**Issue by jonakyd** [nhmood/watson-ruby#128]
it will be useful for 'watch on save' task.

**Comment by nhmood** [comment]
If you use the `-f / --files` and pass a single file (along with the `-u / --update` flag I believe it should only update / post issues for that file. I have tested this with GitHub and Bitbucket.

Is the functionality you are looking for different?

**Comment by jonakyd** [comment]
Thanks! I didn't realize that I can combine those flags, solve my issue by

``` bash
watson -f path/to/my.file -u
```

I'm trying to make a grunt plugin for watson, thanks!
