### ISSUE TITLE
watson --update not working

### ISSUE THREAD

**Issue by sameersegal** [nhmood/watson-ruby#129]
Hey, after I got over the ignore issues, I have been struggling to update my remote with issues. This is a private repo.

```
[ o ] Obtained OAuth Token

[ ! ] Repo information required
      Please provide owner that repo is under followed by repo name
      e.g. owner: nhmood, repo: watson (case sensitive)
      See help or README for more details on GitHub access

Owner: ArtooTrills
Repo: MotherShip

[ o ] Repo successfully accessed

[ + ] Creating label for watson on GitHub...
[ x ] Unable to create label for /ArtooTrills/MotherShip
      Status: 422 - Unprocessable Entity

[ o ] GitHub successfully setup
      Issues will now automatically be retrieved from GitHub by default
      Use -p, --push to post issues to GitHub
      See help or README for more details on GitHub/Bitbucket access
```

Also note, I think you have changed -p to -u. You might want to update the help text above.

`watson -u` or `watson --update` just shows me the regular output from `watson`. Am I missing something?

**Comment by nhmood** [comment]
When you do a `watson -u` or `watson --update` it doesn't tell have any kind of indicator that the issue have been pushed to GitHub (other than if it fails to do so) and from the looks of it everything seems to be getting set up properly. The unable to create a label error occurs if a label of the same name already exists.

I will fix the -p to -u typo in the output after setting up the remotes. 
Are you seeing the issues posted on GitHub?

**Comment by sameersegal** [comment]
Hi, sorry I forgot to mention I don't see any corresponding issues on Github. It is a private repo - does it matter?

**Comment by nhmood** [comment]
To be honest, I have never tested this with a private repo, but I don't see why the API would be any different.

If you are comfortable with Ruby and editing some of the files in the gem I can walk you through some steps to generate some debug information that could help me debug the problem (very simple changes, turning on debug flags to print info)

If not I can try to get my hands on a private repo to see if there is something different with that and the public repos

**Comment by jonakyd** [comment]
@sameersegal 
I also use watson on my private repo, it works for me.
