### ISSUE TITLE
Close issue from code, or seeing issue number in list

### ISSUE THREAD

**Issue by Melindrea** [nhmood/watson-ruby#210]
Nice work!

The first thing I ran into is that it added the issue properly to Github, and once it was closed on Github it showed it as closed properly, but ... I do not appear to be able to close the issue, and it doesn't give me an issue number, which means I would need to go to Github to close and/or figure out the number.

I can see how adding the ability to close issues from the code might be problematic, but if it reports back the issue number, I could commit with "Fixes #x", without needing to leave my terminal.

Is this something that I've either missed, or that's (now?) on the horizon?

**Comment by nhmood** [comment]
Great points, I haven't looked at being able to close the issues from watson yet but it is something I might think about integrating in (either command line option to close like ghi/hub, or something more interactive along with the current output). This is a little bit further down the road though.

However, for now the issue # listing in the output is a great idea, I'm not sure why I wasn't displaying it in the place! Expect to see this feature added fairly soon.

**Comment by Melindrea** [comment]
Nice, thanks =)

**Comment by nhmood** [comment]
@Melindrea it now outputs the issue # on the final output. Still working on issue closing, will update when that comes around.

**Comment by Melindrea** [comment]
:+1:
