### ISSUE TITLE
Github Auth with 2 Step Verification

### ISSUE THREAD

**Issue by lesjames** [nhmood/watson-ruby#212]
I have 2 step verification enabled on my Github account. Watson appears to have issues connection to my account because of it. I tried creating an access token but that didn't work either. Any suggestions?

**Comment by nhmood** [comment]
According to the GitHub API documentation it should be possible ([v3/auth](http://developer.github.com/v3/auth/) at the end) so I will take a look at this.

In the meantime, you can try [creating an access token](https://help.github.com/articles/creating-an-access-token-for-command-line-use) and manually adding the info to your `.watsonrc` file: 

```
[github_api]
API_TOKEN_HERE

[github_repo]
owner_of_repo/repo_name

[github_endponit]
https://api.github.com
```

**Comment by nhmood** [comment]
@lesjames this should be fixed with https://github.com/nhmood/watson-ruby/commit/6bfbfda7b58f929fb842418f65135f928e9fcd15

Let me know if you are still having problems
