### ISSUE TITLE
warning: character class has '-' without escape

### ISSUE THREAD

**Issue by javoire** [nhmood/watson-ruby#214]
For example when trying to parse SQL comments that are "---". 

When running 

```
$ watson
```

Outputs:

```
warning: character class has '-' without escape: /^[["---", "\/\/", "#"]+?\s+?]+\[(\w+)\]\s+-\s+(.+)/
```

The SQL comment array of 

```
['---', '//', '#']
```

becomes

```
['---', '\/\/', '#']
```

So the slashes are escaped but not the dashes

**Comment by javoire** [comment]
Seems like I can't reproduce it anymore though...

**Comment by nhmood** [comment]
This was a problem before but it should have been fixed in https://github.com/nhmood/watson-ruby/commit/2943ddcd0f05395b68eea3f5b1fcf34f9ecc44a7

This change was in the v1.4.2 gem release, maybe your gem was older?

**Comment by javoire** [comment]
Yep, I think I got it on v1.4.1. Cheers
