### ISSUE TITLE
Some ignore patterns seem to not work: can't hide certain subdirectories

### ISSUE THREAD

**Issue by cbowns** [nhmood/watson-ruby#217]
I'm trying to ignore a subdirectory of my project:

```
cbowns% watson | grep -i Third                                    
[ o ]  Third-Party/Crashlytics.framework/Crashlytics
[ o ]  Third-Party/Crashlytics.framework/run
[ o ]  Third-Party/Crashlytics.framework/Headers/Crashlytics.h
[ o ]  Third-Party/Crashlytics.framework/Resources/Info.plist
…
```

but this entry in my project's `.watsonrc` doesn't do the trick:

```
# Ignores
[ignore]
.git
.swp
.DS_Store
*/Images.xcassets
*.xcodeproj/
*.xcworkspace/
Third-Party/
```

Watson version:

```
cbowns% watson -v                                                 
watson v1.4.3
Copyright (c) 2012-2013 goosecode labs
Licensed under MIT, see LICENSE for details

Written by nhmood, see <http://goosecode.com/projects/watson>
```

(I just did a `gem update`)

**Comment by cbowns** [comment]
Of note: the `*/Images.xcassets` entry works great, but I can't hide `Third-Party` for the life of me. I've tried several simple and wildcard patterns.

**Comment by nhmood** [comment]
This was pretty poorly implemented from the start, a bunch of things with the `ignores` weren't working.
I think I fixed them all with the last update and it should support more interesting wildcards (i.e. `src/*/.o`, (all `.o` in any folder under `src`, for example)

Let me know if you are still running into problems and I can take another look

**Comment by cbowns** [comment]
Looks great in 1.5.0, thanks!
