### ISSUE TITLE
Error to connect Asana 

### ISSUE THREAD

**Issue by jmparraguez-haulmer** [nhmood/watson-ruby#249]
I get: Unable to get project info from Asana API
when i try to connect Asana API, i think the problem is in the file asana.rb: line 313.

**Comment by mtford90** [comment]
What does the error look like? I've been using this for a while with no issue.

**Comment by jmparraguez-haulmer** [comment]
In debug mode I found that the error was gsub, was not installed.
now it works

**Comment by mtford90** [comment]
Cool, prob worth raising an issue to improve logging around problems like this. Shouldn't have to enable debug mode to figure out why its failings :)—

**Comment by jmparraguez-haulmer** [comment]
Yes, and it was not easy to find the error, the log in debug mode is quite huuuge!

**Comment by nhmood** [comment]
@jmparra What did you mean by gsub was not installed? I thought it was part of Ruby core?
Also, did you use --debug or --debug github? Either way, you and @mtford90 are right in that the error should be descriptive enough that you don't need to dig into the debug to figure out what the general cause is.

I'll look into adding more descriptive errors to the Asana module.
