### ISSUE TITLE
Is Ruby convention to return 1 or 0 (or -1) on failure/error? [lib/watson/parser.rb]

### ISSUE THREAD

**Issue by nhmood** [nhmood/watson-ruby#75]
**filename** : lib/watson/parser.rb
**line #** : 397
**tag** : review
**md5** : 665255a5ce744fd4fcb805c45f2f4f32

```
            # [review] - Is Ruby convention to return 1 or 0 (or -1) on failure/error?
            debug_print "Couldn't find any recognized extension type\n"
            return false 

        end 


    end
end
```

**Comment by hunterboerner** [comment]
Does this help? http://stackoverflow.com/questions/2793495/returning-true-or-error-message-in-ruby

**Comment by chendrix** [comment]
Returning anything _important_ on failure is anti-convention. It completely violates command/query separation.

**Comment by nhmood** [comment]
Thanks @hunterboerner , that was a useful read/resource! Seems the convention I am using will do.

**Comment by chendrix** [comment]
The convention you are using is completely screwed up. Failure/error need to be isolated to the proper channel, the error channel. Errors **should be** represented by raise/rescues.

**Comment by nhmood** [comment]
@chendrix Do you have any suggested reading material / resources that I can look at for raise/rescues? Or we can chat offline? I'm relatively new to Ruby (this project was my endeavor into it!) :[

**Comment by chendrix** [comment]
If you want a deep-dive into handling exception in Ruby, I highly suggest [Exceptional Ruby](http://exceptionalruby.com/). For low level, this [post on exceptions](http://rubylearning.com/satishtalim/ruby_exceptions.html) and [post on throw/catch](http://rubylearning.com/blog/2011/07/12/throw-catch-raise-rescue-im-so-confused/) (different from raise/rescue)

**Comment by chendrix** [comment]
Also, we can definitely chat offline if you want. Follow me on twitter [@materialdesignr](https://twitter.com/materialdesignr) and we can DM.
