### ISSUE TITLE
Not sure if the way static methods are defined is correct [lib/watson/printer.rb]

### ISSUE THREAD

**Issue by nhmood** [nhmood/watson-ruby#76]
**filename** : lib/watson/printer.rb
**line #** : 23
**tag** : review
**md5** : 75181fe6c6d0bedac0c3a96c684ea9dd

```
    # [review] - Not sure if the way static methods are defined is correct
    #            Ok to have same name as instance methods?
    #            Only difference is where the output gets printed to
    # [review] - No real setup in initialize method, combine it and run method?
        # Include for debug_print (for class methods)
    include Watson
        # Debug printing for this class
    DEBUG = false       
        class << self

    # Include for debug_print (for static methods)
    include Watson
        ###########################################################
```

**Comment by chendrix** [comment]
If by static methods you mean class methods, the traditional way to define them is just

``` ruby
class X
  def self.foo
    bar
  end
end
```

And yes, technically having the same name as instance methods is perfectly fine. I'd question the **need** for them to be the same, and if that points to a larger structural/design issue.

**Comment by nhmood** [comment]
Yes, that is what I meant. For the case in the issue I use the 

``` ruby
class X
class << self
include Watson
  def foo
    bar
  end
end
```

because otherwise I would have to `include Watson` in every method.

I guess there was no reason for keeping the same name for the static/class methods other than to keep printing names consistent. The class method has a variable destination for printing whereas the static method always (and only) prints to STDOUT.

**Comment by chendrix** [comment]
Why not separate out the things that can change from the things that can stay the same? 

Why should the sink for messages not be something that can be passed in?
