### ISSUE TITLE
Comment support

### ISSUE THREAD

**Issue by kyrias** [nhmood/watson-ruby#87]
It would be quite useful if you could browse (and add new) comments to the GitHub issues.

**Comment by hunterboerner** [comment]
Do you mean something like this?

``` ruby
# [bug] - I brokez it
# {user} Oh no!
# {hunterboerner} Yes

def weird_method

end
```

**Comment by nhmood** [comment]
Interesting idea but I'm not sure I can do this and stick with the 'don't touch the code' way that I'm doing things right now. Added todo tag though, will think about it and see if its an option
