### ISSUE TITLE
Source code should use 2-space indentation (not tabs)

### ISSUE THREAD

**Issue by shekibobo** [nhmood/watson-ruby#91]
Code is hard to read/review with 8-space tabs being used. Ruby convention is 2-spaces, and would make this much easier to read/edit.

**Comment by apetresc** [comment]
Just configure your editor to display tabs as 2 spaces, the way I do. This is what Watson's code looks like for me:

![tabs](https://f.cloud.github.com/assets/14872/1594516/1bb72f44-52dc-11e3-89f2-f628e4af1cd2.png)

**Comment by runlevel5** [comment]
It is by common convention that Ruby use 2 spaces indentation, I think it's worth a go to change.

**Comment by nhmood** [comment]
Is there any tool I can use to auto convert all the 4space to 2space?

**Comment by alpaca-tc** [comment]
@joneslee85 :+1: :+1:

**Comment by nhmood** [comment]
Fixed on 48b50969e9
