### ISSUE TITLE
Misleading .watsonrc documentation

### ISSUE THREAD

**Issue by Szeliga** [nhmood/watson-ruby#92]
In the readme file, under the .watsonrc section it says:

[dirs] - This is a newline separated list of directories to ignore.

Where the flags info say that the --dirs flag specifies a list of directories watson should search in.

Was this intended, or is it a typo? :)

**Comment by nhmood** [comment]
Typo! The perils of copy and pasting...
Fixed in 08864d9bbead582120538441af0ba7bdcab5cac9
