### ISSUE TITLE
Please get rid of fade intro on the gh-pages site.

### ISSUE THREAD

**Issue by yesimon** [nhmood/watson-ruby#94]
This is a tool for engineers! Don't waste their time, they just want to get to the point.

:)

**Comment by shyndman** [comment]
Agreed. And it's jumpy when it switches images, losing your place if you're reading the text down below.

Better to give us a YouTube video, so we can seek and pause.

**Comment by nhmood** [comment]
As pretty as it was it has been removed :(
Good to hear from you @yesimon!

@shyndman I was planning on making a YouTube video walking through the use cases but I haven't gotten around to it. The GIFs were meant to give a feel for how the app works before the video, somewhere between a screenshot and a video.

**Comment by shyndman** [comment]
@nhmood I think it did a good job at that. I'm just being picky. :)
