### ISSUE TITLE
Better out-of-the box experience by ignoring binaries and non-source files

### ISSUE THREAD

**Issue by radiospiel** [nhmood/watson-ruby#98]
I tried watson and was immediately hit with #89. While it is probably something that the rub could should handle - instead of raising an exception it could, for example, just print the name of the offending file - I think the outofthebox experience should be much better.

watson should ignore binaries and could try to deduce the binarishness of a file via either file(1) or via its extension (any well-known MIME extension which is, say, image/\* is probably an image). 

watson should also ignore all files that are not going to be checked in because they are .gitignored or are part of a sub repository.

**Comment by nhmood** [comment]
I saw this problem when testing prior to release and thought I fixed it by forcing encoding but I guess it wasn't enough. Should be fixed with 44625bb, sorry for the inconvenience!
